### ISSUE TITLE
any way to check for release candidates?

### ISSUE THREAD

**Issue by facutk** [kriasoft/check-version#6]
We should be able to check that `1.0.0-rc.1` > `1.0.0-rc.0`

**Comment by facutk** [comment]
All of these cases are valid semver https://github.com/omichelsen/compare-versions/blob/master/test/compare.mjs

**Comment by facutk** [comment]
please, review this PR https://github.com/kriasoft/check-version/pull/7

**Comment by koistya** [comment]
@facutk just merged your PR. Thank you!
