### ISSUE TITLE
Migrate set-output to environment files

### ISSUE THREAD

**Issue by froblesmartin** [kriasoft/check-version#9]
Hi! Thanks for your action @koistya ! I just tried it and got some warnings about this.

The lines are https://github.com/kriasoft/check-version/blob/a2c4e002cfd18db8e378fb63d96421062d752f48/main.js#L138-L141, and the warning is:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I may open a PR to change that 😉

**Comment by koistya** [comment]
@froblesmartin good catch! If you can create a PR that would be great!
